const ACTIONS = {
  SET_USER: "SET_USER",
  SET_TOKEN: "SET_TOKEN",
  SET_LOADING: "SET_LOADING",
  SUCCESSFUL_LOGIN: "SUCCESSFUL_LOGIN",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_FAILED: "LOGIN_FAILED",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR",
  LOGOUT: "LOGOUT",
  SET_USER_CONTEXT: "SET_USER_CONTEXT",
  SET_AUTH_STATUS: "SET_AUTH_STATUS",
  SET_ROLE: "SET_ROLE",
  SET_PROFILE_IMAGE: "SET_PROFILE_IMAGE",
  SET_USER_STATUS: "SET_USER_STATUS",
  SET_NOTIFICATIONS: "SET_NOTIFICATIONS",
  SET_USER_DATA: "SET_USER_DATA",
  RESET_STATE: "RESET_STATE",
};

export default ACTIONS;
