// Define role-based route configurations
import {
    AddProduct,
    Inbox,
    Orders,
    OrderTemplate,
    ProductCategories,
    Products,
    Reviews,
    SalesAnalytics,
    Settings,
    SingleCustomer,
    SingleOrder,
    SingleProduct,
    Transactions,
    Timetable,
    Teachers,
    SingleTeacher,
    Subjects,
    Classmates,
    Dashboard,
    ExamResult,
    ExamSchedule,
    Attendance,
    GeneralResult,
    StudentLeave,
    StudentLeaveApply,
    NoticeBoard,
    TeachersReviews,
    TeachersAddReview,

  } from '../../pages';
  
export const roleRoutes = {
    Admin: [
      { id: "admin-dashboard", path: "/", element: <Dashboard /> },
      { id: "admin-products", path: "/products", element: <Products /> },
      // { id: "admin-subjects", path: "/subjects", element: <Subjects /> },
    ],
    Teacher: [
      { id: "teacher-dashboard", path: "/", element: <Dashboard /> },
      { id: "teacher-subjects", path: "/subjects", element: <Subjects /> },
      { id: "teacher-settings", path: "/settings", element: <Settings /> },
      { id: "teacher-notice-board", path: "/notice_board", element: <NoticeBoard /> },
      { id: "teacher-attendance", path: "/attendance", element: <Attendance /> },
      { id: "teacher-timetable", path: "/timetable", element: <Timetable /> },
      { id: "teacher-leave", path: "/leave", element: <StudentLeave /> },
      { id: "teacher-inbox", path: "/inbox", element: <Inbox /> },
    ],
    
    Student: [
      { id: "student-dashboard", path: "/", element: <Dashboard /> },
      { id: "student-products", path: "/products", element: <Products /> },
      { id: "student-add-product", path: "/products/add", element: <AddProduct /> },
      { id: "student-single-product", path: "/products/:id", element: <SingleProduct /> },
      { id: "student-product-categories", path: "/products/categories", element: <ProductCategories /> },
      { id: "student-timetable", path: "/timetable", element: <Timetable /> },
      { id: "student-teachers", path: "/teachers", element: <Teachers /> },
      { id: "student-subjects", path: "/subjects", element: <Subjects /> },
      { id: "student-classmates", path: "/classmates", element: <Classmates /> },
      { id: "student-single-customer", path: "/customers/:id", element: <SingleCustomer /> },
      { id: "student-single-teacher", path: "/teachers/:id", element: <SingleTeacher /> },
      { id: "student-sales-analytics", path: "/sales/analysis", element: <SalesAnalytics /> },
      { id: "student-exam-result", path: "/exam_result", element: <ExamResult /> },
      { id: "student-orders", path: "/orders", element: <Orders /> },
      { id: "student-order-template", path: "/orders/template", element: <OrderTemplate /> },
      { id: "student-single-order", path: "/orders/:id", element: <SingleOrder /> },
      { id: "student-attendance", path: "/attendance", element: <Attendance /> },
      { id: "student-transactions", path: "/transactions", element: <Transactions /> },
      { id: "student-leave", path: "/leave", element: <StudentLeave /> },
      { id: "student-leave-apply", path: "/leave/apply", element: <StudentLeaveApply /> },
      { id: "student-reviews", path: "/reviews", element: <Reviews /> },
      { id: "student-settings", path: "/settings", element: <Settings /> },
      { id: "student-inbox", path: "/inbox", element: <Inbox /> },
      { id: "student-exam-schedules", path: "/exam_schedules", element: <ExamSchedule /> },
      { id: "student-results", path: "/results", element: <GeneralResult /> },
      { id: "student-notice-board", path: "/notice_board", element: <NoticeBoard /> },
      { id: "student-teachers-reviews", path: "/teachers_reviews", element: <TeachersReviews /> },
      { id: "student-review-teacher", path: "/review_teacher", element: <TeachersAddReview /> },
    ],
  };

//   export const userRoutes = roleRoutes[role] || roleRoutes.Student; // Default to Student if role is not recognized