export { default as Dashboard } from "./Dashboard";
export { default as AdminDashboard } from "./AdminDashboard";
export { default as Products } from "./Products";
export { default as AddProduct } from "./AddProduct";
export { default as SingleProduct } from "./SingleProduct";
export { default as ProductCategories } from "./ProductCategories";
export { default as Customers } from "./Customers";
export { default as SingleCustomer } from "./SingleCustomer";
export { default as SalesAnalytics } from "./SalesAnalytics";
export { default as ProductSales } from "./ProductSales";
export { default as Orders } from "./Orders";
export { default as OrderTemplate } from "./OrderTemplate";
export { default as SingleOrder } from "./SingleOrder";
export { default as Suppliers } from "./Suppliers";
export { default as Transactions } from "./Transactions";
export { default as Brands } from "./Brands";
export { default as Reviews } from "./Reviews";
export { default as Settings } from "./Settings";
export { default as Inbox } from "./Inbox";
export { default as Timetable } from "./Timetable";
export { default as Teachers } from "./Teachers";
export { default as SingleTeacher } from "./SingleTeacher";
export { default as Subjects } from "./Subjects";
export { default as Classmates } from "./Classmates";
export { default as SuccessPage } from "./Success";
export { default as ExamResult } from  "./ExamResult";
export { default as ExamSchedule } from  "./ExamSchedule";
export { default as Attendance } from  "./Attendance";
export { default as GeneralResult } from  "./GeneralResult";
export { default as StudentLeave } from "./StudentLeave";
export { default as StudentLeaveApply} from "./StudentLeaveApply";
export { default as NoticeBoard} from "./NoticeBoard";
export { default as TeachersReviews } from "./TeachersReview";
export { default as TeachersAddReview} from "./TeachersAddReview";
export { default as ResetLinkSent } from "./ResetLinkSent"
